<?xml version="1.0" encoding="utf-8"?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xml:id="zend.exception.using"><info><title>Использование исключений</title></info>

    

    <para>
        Все исключения, бросаемые классами Zend Framework, должны быть
        наследниками основного класса Zend_Exception.
    </para>

    <example xml:id="zend.exception.using.example"><info><title>Пример отлова исключения</title></info>
        
        <programlisting language="php"><![CDATA[
try {
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e->getMessage() . "\n";
    // other code to recover from the failure.
}

        ]]></programlisting>
    </example>

    <para>
        Более детальную информацию о том, какие методы могут бросать исключения,
        условия, при которых бросаются исключения, и о том, какие классы
        исключений наследуют от Zend_Exception, можно найти в документации по
        соответсвующей компоненте Zend Framework.
    </para>

</section>
