<?xml version="1.0" encoding="utf-8"?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xml:id="zend.exception.previous"><info><title>Exceptions précédentes</title></info>
    

    <para>
        Depuis Zend Framework 1.10, <classname>Zend_Exception</classname> utilise les exceptions PHP 5.3
        concernant l'exception précédente. Simplement, dans un bloc <methodname>catch</methodname>, il est
        possible d'envoyer une exception faisant référence à la précédente, ce qui améliore le contexte de
        débogage. Ce support dans Zend Framework apporte le support complet de PHP 5.3 concernant les exceptions.
    </para>

    <para>
        L'exception précedente s'utilise comme troisième paramètre du constructeur de la classe Exception.
    </para>

    <example xml:id="zend.exception.previous.example"><info><title>Exceptions précedentes</title></info>
        

        <programlisting language="php"><![CDATA[
try {
    $db->query($sql);
} catch (Zend_Db_Statement_Exception $e) {
    if ($e->getPrevious()) {
        echo '[' . get_class($e)
            . '] a comme exception précédente ['
            . get_class($e->getPrevious())
            . ']' . PHP_EOL;
    } else {
        echo '[' . get_class($e)
            . '] n'a pas d'exception qui la précède'
            . PHP_EOL;
    }

    echo $e;
    // affiche toutes les exception à commencer par la première, puis
    // dépile.
}
]]></programlisting>
    </example>
</section>
